apiVersion: v1
kind: Pod
metadata:
  name: emptydir-share-demo  # Name of the Pod
spec:
  volumes:
    - name: shared-storage   # Shared volume name
      emptyDir: {}           # Temporary storage (deleted when Pod is deleted)
  containers:
    - name: writer           # First container (writes data)
      image: duvindune/repo1:v1
      volumeMounts:
        - name: shared-storage
          mountPath: /duvindu   # Writer writes data here
    - name: reader           # Second container (reads data)
      image: duvindune/repo2:v1
      volumeMounts:
        - name: shared-storage  # Mount the same shared volume
          mountPath: /niduvara      # Reader reads data from here



# kubectl exec -it emptydir-share-demo -c writer -- /bin/bash
# echo "Hello from writer container" > /duvindu/test.txt
# cat /duvindu/test.txt
# exit

# kubectl exec -it emptydir-share-demo -c reader -- /bin/bash
# cat /niduvara/test.txt