apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginx  # match with service template, rs
  annotations:
    description: "nginx pod for learning"
spec:
  containers: 
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80





