apiVersion: v1
kind: Service
metadata:
  name: nginx-pod
  labels:
    app: nginx        # This will show Services with label app=nginx.
                      # kubectl get svc -l app=nginx
spec:
  type: NodePort
  ports:              
    - port: 80        # port on which the Service listens for incoming traffic.
      protocol: TCP
      targetPort: 80  # where traffic should re-direct
  selector: 
    app: nginx        # service gonna looks pods have this label
