apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1250m"
    requests.memory: "320Mi"
    limits.cpu: "2500m"
    limits.memory: "640Mi"
