apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: stateful-svc  # link with service.yml
  replicas: 2
  selector:
    matchLabels:
      app: web 
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: django-app
          image: duvindune/repo2:v1
          volumeMounts:
            - name: data ## (a)
              mountPath: /data
  volumeClaimTemplates:  # to create a persistence storage for pods
    - metadata:
        name: data        ## (b), a & b should same
      spec:
        accessModes: [ "ReadWriteOnce" ] # how used by pods
        resources:
          requests:
            storage: 1Gi


# /usr/share/nginx/html is the default folder inside 
# nginx where it serves web pages, and mounting a 
# volume here allows the container to serve files 
# from that persistent storage.


# ✅ You are replacing nginx’s default content folder with your volume


# The original nginx files are hidden/replaced
# Now nginx reads files from your volume instead