# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: django-deployment
#   labels:
#     app: django
#   annotations:
#     "kubernetes.io/change-cause": "initial state"
# spec:
#   replicas: 5
#   selector: 
#     matchLabels: 
#       app: django      # which pods to be managed
#   template:
#     metadata:
#       labels:
#         app: django    # Ensures newly created Pods match the selector.
#     spec:
#       containers:
#       - name: django
#         image: duvindune/repo6:v1.0
#         ports:
#           - containerPort: 8000



apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django
  annotations:
    "kubernetes.io/change-cause": "initial state"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: duvindune/repo6:v1.0
        ports:
          - containerPort: 8000

        env:
          - name: SECRET_KEY
            valueFrom:
              # configMapKeyRef:
              secretKeyRef:
                name: dj-app
                key: SECRET_KEY

          - name: DEBUG
            valueFrom:
              # configMapKeyRef:
              secretKeyRef:
                name: dj-app
                key: DEBUG