apiVersion: v1
kind: Pod
metadata:
  name: dj-pod
  labels:
    app: dj-app
spec:
  containers:
    - name: dj-app
      image: duvindune/repo6:v1.0
      env:
        - name: SECRET_KEY # what your app (Django/nginx/etc.) will see as the env variable.
          valueFrom:
            configMapKeyRef:
              name: dj-app # which ConfigMap to read from.
              key: SECRET_KEY # which key inside that ConfigMap to use.
        - name: DEBUG # what your app (Django/nginx/etc.) will see as the env variable.
          valueFrom:
            configMapKeyRef:
              name: dj-app # which ConfigMap to read from.
              key: DEBUG # which key inside that ConfigMap to use.
        # - name: SECRET_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: dj-app
        #       key: SECRET_KEY
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
      - containerPort: 8000